### ISSUE TITLE
商用版权? 官方下载？

### ISSUE THREAD

**Issue by whybd** [CyanoHao/Resource-Han-Rounded#14]
你好！
 
我们是位在新加坡的一家设计公司，有意采你设计的字体用于商业包装设计。
请问需要获取怎样的商用版权？
可以提供最好的官方下载链接？谢谢！

**Comment by CyanoHao** [comment]
https://github.com/CyanoHao/Resource-Han-Rounded/blob/master/LICENSE.md

此字体以 SIL Open Font License 分发，无需再额外获取商用授权。
