### ISSUE TITLE
关于本款字体是否个人以及企业商用的问题

### ISSUE THREAD

**Issue by Safer-7** [CyanoHao/Resource-Han-Rounded#16]
您好，由于不知道别的联系方式，所以只能在这里留言，请问Resource-Han-Rounded这个字体是否是对个人以及企业永久商用免费的呢？期待您的答复~

**Comment by CyanoHao** [comment]
字体以 SIL OFL 授权，商用免费。注意不能单独销售（可以作为其它软件的一部分销售）；如果修改字体文件，则必须以同样协议授权。
