### ISSUE TITLE
Font name too long

### ISSUE THREAD

**Issue by NightFurySL2001** [CyanoHao/Resource-Han-Rounded#2]
The font name is too long and exceeds the 31-character limit of OpenType fonts. (i.e. Resource Han Rounded SC Extralight - 34 characters) and showed up as 1 corrupted font and 1 shortened font.
![image](https://user-images.githubusercontent.com/33471049/71539090-fcf24300-2971-11ea-9c57-0fc4746056c5.png)
![image](https://user-images.githubusercontent.com/33471049/71539093-05e31480-2972-11ea-81c3-842953d76400.png)

**Comment by CyanoHao** [comment]
I created a new branch for MS Office with shorter font name.
[MSOffice-RHR](https://github.com/CyanoHao/MSOffice-RHR/releases)

![image](https://user-images.githubusercontent.com/14287996/71542877-c84cae80-29a6-11ea-9fd0-bec31c875866.png)

**Comment by NightFurySL2001** [comment]
Issue is fixed. Thank you.
Please add the repo link for MS Office in this repo main page for ease of access and warn of others of this bug.

**Comment by NightFurySL2001** [comment]
Issue fixed with #4 .
